In [1]:
print("Python3.8")

Python3.8


In [5]:
import import_ipynb
import moduleabc
moduleabc.add(3,5)


importing Jupyter notebook from moduleabc.ipynb


8

In [26]:
import numpy as np

data = np.random.randn(1,4)
print(data,'\n')

print(data+data,'\n')

print(data *10,'\n')

print(data.shape,'\n')

print(data.dtype,'\n')

print(data.ndim,'\n')



[[-0.57509137 -0.38400156  0.57797989 -1.71970546]] 

[[-1.15018274 -0.76800312  1.15595978 -3.43941091]] 

[[ -5.75091371  -3.84001561   5.77979892 -17.19705457]] 

(1, 4) 

float64 

2 

