In [12]:
#Numpy start

import numpy as np
data = np.random.randn(2, 3)
print(data ,'\n') 
print(data+data , '\n') 
print(data * 10 , '\n')
print(data.shape, '\n')
print(data.dtype , '\n')
print(data.ndim, '\n')


[[ 1.23906297 -1.44138457  0.68554891]
 [-0.52361926 -1.23510735  1.29778584]] 

[[ 2.47812594 -2.88276913  1.37109783]
 [-1.04723853 -2.4702147   2.59557169]] 

[[ 12.39062971 -14.41384567   6.85548914]
 [ -5.23619264 -12.35107348  12.97785845]] 

(2, 3) 

float64 

2 



In [20]:
#zero and empty

print(np.zeros(10) , "\n")

print(np.zeros((3,6)), "\n")

print(np.zeros((2,3,6)), "\n")


print(np.empty(5) , "\n") #garbage values can be assigned while using empty

print(np.empty((3,6)) , "\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [31]:
#arrange - like range in normal python

print(np.arange(9), "\n")
print(np.arange(18).reshape(6,3),"\n")
print(np.arange(18).reshape(3,6),"\n")


[0 1 2 3 4 5 6 7 8] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 



In [40]:
#changing data type
arr = np.array([1,2,3,4,5])
print(arr.astype(np.float64))

arr2= np.array(["1","2","3","4","5"])
print(arr2.astype(np.float64))

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [41]:
#operations on array and datatype

arr = np.array([4,2,6,8] , dtype='int64')
print(arr * 2 ,'\n')
print(arr * arr ,'\n')
print(2/arr  ,'\n')
print(arr ** 2 ,'\n')
print(np.sqrt(arr) , '\n')
print(np.exp(arr) , '\n')
print(np.mean(arr) , '\n')
print(np.sort(arr) , '\n')
print(np.sum(arr) , '\n')
print(np.cumsum(arr) , '\n')


arr2= np.array([1,2,3,4])

print(arr > arr2)

[ 8  4 12 16] 

[16  4 36 64] 

[0.5        1.         0.33333333 0.25      ] 

[16  4 36 64] 

[2.         1.41421356 2.44948974 2.82842712] 

[  54.59815003    7.3890561   403.42879349 2980.95798704] 

5.0 

[2 4 6 8] 

20 

[ 4  6 12 20] 

[ True False  True  True]


In [42]:
# indexing and slicing

arr=np.arange(10)
print(arr)

arr2=arr[5:8]
print(arr2)

arr[:3]=0  # assigning specific value to some indexes of array
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [108]:
#boolean example --imp- the number of array and names shoule be same

namesArr= np.array(["Umar", "Umair", "Nouroz", "Ali","Umar"])
numArr=np.random.randn(5,3)
print(numArr , '\n')
print(namesArr , '\n')
print(namesArr == "Umar" , '\n')
print(numArr[namesArr=="Umar"] , '\n')
print(numArr[~(namesArr=="Umar")], '\n')
print(np.unique(namesArr),'\n')  # unique provides unique elements back and sorts them alphabetically

[[-1.48996757  0.67436014 -0.29397452]
 [ 0.01436092  0.04158438 -1.36624663]
 [ 1.15214238 -0.63827616  1.94497463]
 [ 0.50279099  1.30619832  1.49055136]
 [ 0.30689239 -0.09440126 -1.25076309]] 

['Umar' 'Umair' 'Nouroz' 'Ali' 'Umar'] 

[ True False False False  True] 

[[-1.48996757  0.67436014 -0.29397452]
 [ 0.30689239 -0.09440126 -1.25076309]] 

[[ 0.01436092  0.04158438 -1.36624663]
 [ 1.15214238 -0.63827616  1.94497463]
 [ 0.50279099  1.30619832  1.49055136]] 

['Ali' 'Nouroz' 'Umair' 'Umar'] 



In [102]:
arr1= np.random.randn(4)
print(arr1 , '\n')
arr2= np.random.randn(4)
print(arr2 , '\n')
print(np.maximum(arr1,arr2), '\n')
print(np.minimum(arr2,arr1), '\n')

[-1.31219923  0.3114249  -0.64400874 -0.0641869 ] 

[ 0.14812246 -0.53896025  0.05679158 -0.33127801] 

[ 0.14812246  0.3114249   0.05679158 -0.0641869 ] 

[-1.31219923 -0.53896025 -0.64400874 -0.33127801] 

